package com.nutrivision.app.ui.auth

import android.content.Intent
import android.os.Bundle
import android.util.Patterns
import android.view.View
import android.widget.Toast
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInAccount
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.android.material.button.MaterialButton
import com.google.android.material.textfield.TextInputEditText
import com.google.android.material.textfield.TextInputLayout
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.firestore.FirebaseFirestore
import com.nutrivision.app.R
import com.nutrivision.app.ui.main.MainActivity

class LoginActivity : AppCompatActivity() {

    private lateinit var auth: FirebaseAuth
    private lateinit var db: FirebaseFirestore
    private lateinit var googleSignInClient: GoogleSignInClient

    // Launcher for the Google Sign-In intent
    private val googleSignInLauncher = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
        if (result.resultCode == RESULT_OK) {
            val task = GoogleSignIn.getSignedInAccountFromIntent(result.data)
            try {
                val account = task.getResult(ApiException::class.java)!!
                firebaseAuthWithGoogle(account.idToken!!)
            } catch (e: ApiException) {
                Toast.makeText(this, "Google Sign In failed: ${e.message}", Toast.LENGTH_SHORT).show()
            }
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_login)

        auth = FirebaseAuth.getInstance()
        db = FirebaseFirestore.getInstance()

        // 1. Configure Google Sign In
        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(getString(R.string.default_web_client_id)) // Automatically generated by Firebase plugin
            .requestEmail()
            .build()
        googleSignInClient = GoogleSignIn.getClient(this, gso)

        val etEmail = findViewById<TextInputEditText>(R.id.etEmail)
        val etPassword = findViewById<TextInputEditText>(R.id.etPassword)
        val tilEmail = findViewById<TextInputLayout>(R.id.tilEmail)
        val tilPassword = findViewById<TextInputLayout>(R.id.tilPassword)
        val btnLogin = findViewById<MaterialButton>(R.id.btnLogin)
        val btnGoogleSignIn = findViewById<MaterialButton>(R.id.btnGoogleSignIn)
        val btnPhoneSignIn = findViewById<MaterialButton>(R.id.btnPhoneLogin)
        val tvRegister = findViewById<View>(R.id.tvRegisterPrompt)
        val tvForgotPassword = findViewById<View>(R.id.tvForgotPassword)
        val progressBar = findViewById<View>(R.id.progressBar)

        btnLogin.setOnClickListener {
            val email = etEmail.text.toString().trim()
            val password = etPassword.text.toString().trim()
            tilEmail.error = null
            tilPassword.error = null

            if (email.isBlank() || !Patterns.EMAIL_ADDRESS.matcher(email).matches()) {
                tilEmail.error = "Enter a valid email"
                return@setOnClickListener
            }
            if (password.isBlank()) {
                tilPassword.error = "Password is required"
                return@setOnClickListener
            }

            progressBar.visibility = View.VISIBLE
            btnLogin.isEnabled = false
            btnGoogleSignIn.isEnabled = false
            btnPhoneSignIn.isEnabled = false
            btnLogin.text = "Signing in..."
            auth.signInWithEmailAndPassword(email, password).addOnCompleteListener { task ->
                progressBar.visibility = View.GONE
                btnLogin.isEnabled = true
                btnGoogleSignIn.isEnabled = true
                btnPhoneSignIn.isEnabled = true
                btnLogin.text = getString(R.string.login_btn)
                if (task.isSuccessful) navigateToMain()
                else Toast.makeText(this, "Error: ${task.exception?.message}", Toast.LENGTH_SHORT).show()
            }
        }

        btnPhoneSignIn.setOnClickListener {
            startActivity(Intent(this, PhoneLoginActivity::class.java))
        }
        btnGoogleSignIn.setOnClickListener {
            progressBar.visibility = View.VISIBLE
            btnGoogleSignIn.isEnabled = false
            btnLogin.isEnabled = false
            googleSignInLauncher.launch(googleSignInClient.signInIntent)
        }

        tvForgotPassword.setOnClickListener {
            val email = etEmail.text.toString().trim()
            if (email.isNotEmpty() && Patterns.EMAIL_ADDRESS.matcher(email).matches()) {
                auth.sendPasswordResetEmail(email).addOnSuccessListener {
                    Toast.makeText(this, "Reset link sent!", Toast.LENGTH_SHORT).show()
                }
            } else {
                tilEmail.error = "Enter your email first"
            }
        }

        tvRegister.setOnClickListener {
            startActivity(Intent(this, RegisterActivity::class.java))
        }
    }

    private fun firebaseAuthWithGoogle(idToken: String) {
        val credential = GoogleAuthProvider.getCredential(idToken, null)
        auth.signInWithCredential(credential).addOnCompleteListener(this) { task ->
            if (task.isSuccessful) {
                val user = auth.currentUser
                checkAndCreateFirestoreUser(user?.uid, user?.displayName, user?.email)
            } else {
                findViewById<View>(R.id.progressBar).visibility = View.GONE
                Toast.makeText(this, "Firebase Auth Failed", Toast.LENGTH_SHORT).show()
            }
        }
    }

    private fun checkAndCreateFirestoreUser(uid: String?, name: String?, email: String?) {
        if (uid == null) return
        db.collection("users").document(uid).get().addOnSuccessListener { doc ->
            if (doc.exists()) {
                navigateToMain()
            } else {
                val user = hashMapOf("uid" to uid, "name" to (name ?: "User"), "email" to (email ?: ""))
                db.collection("users").document(uid).set(user).addOnSuccessListener { navigateToMain() }
            }
        }
    }

    private fun navigateToMain() {
        val intent = Intent(this, MainActivity::class.java)
        intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK
        startActivity(intent)
        finish()
    }
}